language: python
sudo: false
branches:
only:
        - master
python:
        - 2.7
        - 3.4
        - 3.5
before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p ./miniconda
    - export PATH=`pwd`/miniconda/bin:$PATH
    - conda update --yes conda
    - conda create -y -q -n test-env python=$TRAVIS_PYTHON_VERSION pip nose
    - source activate test-env

install:
    - python setup.py install

script:
    - python -c 'import pysal_examples; print(pysal_examples._version)'
    - python setup.py sdist > /dev/null
    - nosetests pysal_examples/
 
notifications:
    email:
        recipients:
            - sjsrey@gmail.com
        on_success: change
        on_faliure: always

